### ISSUE TITLE
Missing message

### ISSUE THREAD

**Issue by JensRantil** [garybernhardt/expecter#11]
I like this library and bookmarked it a while ago. I was gonna use it just now but realize the only thing holding me back is that `expect` does not enable me to write a message about the assert in question, like `assert` does. My question is, two-fold:
- Can I do this easily?
- Has there been any discussions about this?

I'd love to hear your thought about this.

**Comment by garybernhardt** [comment]
You can't do it currently, and this is actually the first time it's come up. I'd just use an assertion if I wanted a custom message. There's not really anywhere to put a big string argument in the Expecter syntax.

To editorialize: the concept of "assertion message" doesn't even exist in RSpec and similar systems. This is a feature: your test name should describe what's happening. The test should be a few (definitely fewer than 10; hopefully significantly fewer) lines of very clear code showing how it happens.

**Comment by JensRantil** [comment]
> You can't do it currently, and this is actually the first time it's come up. I'd just use an assertion if I wanted a custom message. There's not really anywhere to put a big string argument in the Expecter syntax.

Aight. Since I find it hard to implement I'm closing this. Reopen if you'd ever find it useful.

> To editorialize: the concept of "assertion message" doesn't even exist in RSpec and similar systems. This is a feature: your test name should describe what's happening. The test should be a few (definitely fewer than 10; hopefully significantly fewer) lines of very clear code showing how it happens.

Interesting. I did not know this. I was, too, thinking about the fact that maybe my assertions weren't clear enough if I'd need a message for them every time.
