### ISSUE TITLE
Expecter for types

### ISSUE THREAD

**Issue by JensRantil** [garybernhardt/expecter#12]
I am converting an application to Python 3. This involves adding a lot of

```
assert isinstance(variable, bytes)
```

. Sadly, the type is not printed when the assertion fails. Sounds like a perfect match for expecter, you agree? :)

Proposed syntax:

```
expect(variable).is_instance_of(bytes)
```

**Comment by sigmavirus24** [comment]
This already exists. 

``` python
expect(var).isinstance(bytes)
```

**Comment by JensRantil** [comment]
Oh! Sweet! Is this documented elsewhere than in code?

**Comment by sigmavirus24** [comment]
I don't think so unfortunately.

@garybernhardt any chance of accepting a PR creating documentation for readthedocs.org?

**Comment by garybernhardt** [comment]
@sigmavirus24, sure!

**Comment by sigmavirus24** [comment]
@garybernhardt working on this on my docs branch

And you can view them [here](http://expecter.readthedocs.org/en/latest/)

**Comment by garybernhardt** [comment]
Full API docs are now up at: http://expecter-gadget.readthedocs.org/en/latest/
