### ISSUE TITLE
Newlines in expectation failures aren't expected

### ISSUE THREAD

**Issue by garybernhardt** [garybernhardt/expecter#3]
This really sucks for multi-line strings. Example:

```
>>> expect("foo\nbar") == 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.6/site-packages/expecter-0.2.1-py2.6.egg/expecter.py", line 18, in     __eq__
    'Expected %s but got %s' % (repr(other), repr(self._actual)))
AssertionError: Expected 0 but got 'foo\nbar'
```

**Comment by CharString** [comment]
Does this really suck?
I've overlooked differences in strings because they were printed, and the differences were in non-printable chars.

What would help imho, is aligning them, by having them start at a newline.

**Comment by garybernhardt** [comment]
It's bad times when the strings are long. When you have 500 characters of JSON and it prints them on one line, you're hosed. RSpec gets around this by showing a diff:

```
     Failure/Error: "foo\nbar".should == "foo\nbaz"
       expected: "foo\nbaz"
            got: "foo\nbar" (using ==)
       Diff:
       @@ -1,3 +1,3 @@
        foo
       -baz
       +bar
```

which is nice, but also would probably require more code than currently exists in Expecter. So maybe it's best to leave it alone or make them line up as you suggest.

**Comment by garybernhardt** [comment]
No one else seems bothered by this; nevermind!

**Comment by CharString** [comment]
Large strings do suck, though..
We could use [difflib.unified_diff](http://docs.python.org/library/difflib.html#difflib.unified_diff) to do what RSpec does.
