### ISSUE TITLE
Expectation Decorator

### ISSUE THREAD

**Issue by kennethreitz** [garybernhardt/expecter#9]
Would allow for this:

``` python
@expecter.expectation
def can_meow(o):
    assert o == 'thing

```

**Comment by garybernhardt** [comment]
That will work now if you use `add_expectation` as a decorator. I think that this is a very bad thing to do, though. Decorators are for wrapping, not for triggering global destructive actions...

**Comment by kennethreitz** [comment]
Nice.

Yeah, ideally it wouldn't be module-level registering.

**Comment by garybernhardt** [comment]
I didn't want to make it global, but I couldn't find a scheme for localizing expectation definitions that wasn't like 10x the complexity of the rest of Expecter combined. :(
